// 命名规则：模块路径_方法名,例如ARCHIVE_REGOIN_GET_COUNTRY

//公共
export const COMMON_CHANGE_LANGUAGE = 'COMMON_CHANGE_LANGUAGE';
export const COMMON_JUDGVE_MOBILE = 'COMMON_JUDGVE_MOBILE';
export const COMMON_DESTROY_TRENDVALUE_LIST = 'COMMON_DESTROY_TRENDVALUE_LIST';
export const COMMON_DESTROY_TRENDSMULTI_TESTPOINTS = 'COMMON_DESTROY_TRENDSMULTI_TESTPOINTS';

// 档案管理-地理区域
export const ARCHIVE_REGOIN_GET_COUNTRY = 'ARCHIVE_REGOIN_GET_COUNTRY';
export const ARCHIVE_REGOIN_GET_PROVINCE = 'ARCHIVE_REGOIN_GET_PROVINCE';
export const ARCHIVE_REGOIN_GET_REGION_INFO = 'ARCHIVE_REGOIN_GET_REGION_INFO';

// 档案管理-电力公司
export const ARCHIVE_COMPANY_GET_COMPANY_INFO = 'ARCHIVE_COMPANY_GET_COMPANY_INFO';
export const ARCHIVE_COMPANY_ADD_EDIT_COMPANY_INFO = 'ARCHIVE_COMPANY_ADD_EDIT_COMPANY_INFO';
export const ARCHIVE_COMPANY_DELETE_COMPANY_INFO = 'ARCHIVE_COMPANY_DELETE_COMPANY_INFO';

// 档案管理-变电站
export const ARCHIVE_SUBSTATION_GET_SUBSTATION_INFO = 'ARCHIVE_SUBSTATION_GET_SUBSTATION_INFO';
export const ARCHIVE_SUBSTATION_ADD_EDIT_SUBSTATION_INFO =
    'ARCHIVE_SUBSTATION_ADD_EDIT_SUBSTATION_INFO';
export const ARCHIVE_SUBSTATION_DELETE_SUBSTATION_INFO =
    'ARCHIVE_SUBSTATION_DELETE_SUBSTATION_INFO';
export const ARCHIVE_SUBSTATION_UPLOAD_SUBSTATION_INFO =
    'ARCHIVE_SUBSTATION_UPLOAD_SUBSTATION_INFO';
export const ARCHIVE_SUBSTATION_UPLOAD_SUBSTATION_SVG = 'ARCHIVE_SUBSTATION_UPLOAD_SUBSTATION_SVG';

// 档案管理-间隔单元
export const ARCHIVE_BAY_GET_BAY_INFO = 'ARCHIVE_BAY_GET_BAY_INFO';
export const ARCHIVE_BAY_ADD_EDIT_BAY_INFO = 'ARCHIVE_BAY_ADD_EDIT_BAY_INFO';
export const ARCHIVE_BAY_DELETE_BAY_INFO = 'ARCHIVE_BAY_DELETE_BAY_INFO';

// 档案管理-电力设备
export const ARCHIVE_DEVICE_GET_DEVICE_INFO = 'ARCHIVE_DEVICE_GET_DEVICE_INFO';
export const ARCHIVE_DEVICE_ADD_EDIT_DEVICE_INFO = 'ARCHIVE_DEVICE_ADD_EDIT_DEVICE_INFO';
export const ARCHIVE_DEVICE_DELETE_DEVICE_INFO = 'ARCHIVE_DEVICE_DELETE_DEVICE_INFO';
export const ARCHIVE_DEVICE_GET_DEVICE_TYPE_AND_SUM = 'ARCHIVE_DEVICE_GET_DEVICE_TYPE_AND_SUM';
export const ARCHIVE_DEVICE_GET_DEVICE_LIST_BY_SID_DTYPE =
    'ARCHIVE_DEVICE_GET_DEVICE_LIST_BY_SID_DTYPE';
export const ARCHIVE_ARCHIVE_GENERATEDEFPOINTS = 'ARCHIVE_ARCHIVE_GENERATEDEFPOINTS';

// 档案管理-监测点
export const ARCHIVE_TESTPOINT_GET_TESTPOINT_INFO = 'ARCHIVE_TESTPOINT_GET_TESTPOINT_INFO';
export const ARCHIVE_TESTPOINT_ADD_EDIT_TESTPOINT_INFO =
    'ARCHIVE_TESTPOINT_ADD_EDIT_TESTPOINT_INFO';
export const ARCHIVE_TESTPOINT_DELETE_TESTPOINT_INFO = 'ARCHIVE_TESTPOINT_DELETE_TESTPOINT_INFO';

// 档案管理-导航树
export const ARCHIVE_TREE_GET_CHILDREN_NODE = 'ARCHIVE_TREE_GET_CHILDREN_NODE';
export const ARCHIVE_TREE_GET_ARCHIVE_TREE = 'ARCHIVE_TREE_GET_ARCHIVE_TREE';
export const ARCHIVE_TREE_SET_MODULE_STATE_CACHE = 'ARCHIVE_TREE_SET_MODULE_STATE_CACHE';
export const ARCHIVE_TREE_CHANGE_GLOBAL_CACHE = 'ARCHIVE_TREE_CHANGE_GLOBAL_CACHE';
export const ARCHIVE_TREE_REFRESH_DATA = 'ARCHIVE_TREE_REFRESH_DATA';
export const ARCHIVE_TREE_CHECK_DATA = 'ARCHIVE_TREE_CHECK_DATA';
export const ARCHIVE_TREE_SSD_STRUCTRUE_QUERY = 'ARCHIVE_TREE_SSD_STRUCTRUE_QUERY';

// 档案管理-通用类型
export const ARCHIVE_COMMON_TYPE_GET_VOLTAGE_CLASS = 'ARCHIVE_COMMON_TYPE_GET_VOLTAGE_CLASS';
export const ARCHIVE_COMMON_TYPE_GET_DEVICE_TYPES = 'ARCHIVE_COMMON_TYPE_GET_DEVICE_TYPES';
export const ARCHIVE_COMMON_TYPE_QUERY_VOLTAGE_LEVEL = 'ARCHIVE_COMMON_TYPE_QUERY_VOLTAGE_LEVEL';
export const ARCHIVE_COMMON_TYPE_QUERY_DEVICE_TYPE = 'ARCHIVE_COMMON_TYPE_QUERY_DEVICE_TYPE';
export const ARCHIVE_COMMON_TYPE_QUERY_STRUCTURAL_STYLE =
    'ARCHIVE_COMMON_TYPE_QUERY_STRUCTURAL_STYLE';
export const ARCHIVE_COMMON_TYPE_QUERY_SENSOR_TYPE = 'ARCHIVE_COMMON_TYPE_QUERY_SENSOR_TYPE';
export const ARCHIVE_COMMON_TYPE_QUERY_CHANNEL_TYPE = 'ARCHIVE_COMMON_TYPE_QUERY_CHANNEL_TYPE';
export const ARCHIVE_COMMON_TYPE_QUERY_BAY_TYPE = 'ARCHIVE_COMMON_TYPE_QUERY_BAY_TYPE';
export const ARCHIVE_COMMON_TYPE_QUERY_PHASE = 'ARCHIVE_COMMON_TYPE_QUERY_PHASE'; //相别
export const ARCHIVE_COMMON_TYPE_QUERY = 'ARCHIVE_COMMON_TYPE_QUERY';
export const ARCHIVE_COMMON_TYPE_KIND_GET = 'ARCHIVE_COMMON_TYPE_KIND_GET';
export const ARCHIVE_COMMON_TYPE_ADDORUPDATE = 'ARCHIVE_COMMON_TYPE_ADDORUPDATE';
export const ARCHIVE_COMMON_TYPE_DELETE = 'ARCHIVE_COMMON_TYPE_KIND_DELETE';

// 测点模板管理
export const ARCHIVE_TESTPOINT_TEMPLATE_QUERY = 'ARCHIVE_TESTPOINT_TEMPLATE_QUERY';
export const ARCHIVE_TESTPOINT_TEMPLATE_ADDORUPDATE = 'ARCHIVE_TESTPOINT_TEMPLATE_ADDORUPDATE';
export const ARCHIVE_TESTPOINT_TEMPLATE_DELETE = 'ARCHIVE_COMMON_TYPE_KIND_DELETE';
// 测试规章管理/测点模板细节管理
export const ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_GET_DEVICETYPELIST =
    'ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_GET_DEVICETYPELIST';
export const ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_QUERY = 'ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_QUERY';
export const ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_ADDORUPDATE =
    'ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_ADDORUPDATE';
export const ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_DELETE = 'ARCHIVE_TESTPOINT_TEMPLATE_DETAIL_DELETE';
export const ARCHIVE_TESTPOINT_TEMPLATE_UPDATE_ISINUSE_BACKGROUND =
    'ARCHIVE_TESTPOINT_TEMPLATE_UPDATE_ISINUSE_BACKGROUND';

//SVG
export const ARCHIVE_SVG = 'ARCHIVE_SVG';

export const FILEMANAGER_UPLOAD = 'FILEMANAGER_UPLOADE';

// 用户权限
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';

//任务管理
export const TASKMANAGER_CLEAR_ON_SUBMIT = 'TASKMANAGER_CLEAR_ON_SUBMIT';
export const TASKMANAGER_GET_CREATETASK_TASK_LIST = 'TASKMANAGER_GET_CREATETASK_TASK_LIST';
export const TASKMANAGER_QUERY_HISTORY_TASK_LIST = 'TASKMANAGER_QUERY_HISTORY_TASK_LIST';
export const TASKMANAGER_QUERY_TASK_LIST = 'TASKMANAGER_QUERY_TASK_LIST';
export const TASKMANAGER_QUERY_TASK_DETAIL = 'TASKMANAGER_QUERY_TASK_DETAIL';
export const TASKMANAGER_CREATE_TASK = 'TASKMANAGER_CREATE_TASK';
export const TASKMANAGER_SCRATCH_TASK = 'TASKMANAGER_SCRATCH_TASK';
export const TASKMANAGER_TASK_STATUS_CHANGE = 'TASKMANAGER_TASK_STATUS_CHANGE';
export const TASKMANAGER_DELETE_TASK = 'TASKMANAGER_DELETE_TASK';
export const TASKMANAGER_GET_TASK_UPDATE = 'TASKMANAGER_GET_TASK_UPDATE';
export const TASKMANAGER_GET_TASK_BY_DEVICE = 'TASKMANAGER_GET_TASK_BY_DEVICE';
export const TASKMANAGER_GET_TASK_LIFECYCLE_STATUS = 'TASKMANAGER_GET_TASK_LIFECYCLE_STATUS';
export const TASKMANAGER_TASKVIEW_QUERY_TASK_DEVICE_DETAIL =
    'TASKMANAGER_TASKVIEW_QUERY_TASK_DEVICE_DETAIL';
export const TASKMANAGER_TASKVIEW_GET_TASK_TESTPOINT = 'TASKMANAGER_TASKVIEW_GET_TASK_TESTPOINT';
export const TASKMANAGER_TASKVIEW_GET_TASK_TESTDATA = 'TASKMANAGER_TASKVIEW_GET_TASK_TESTDATA';
export const TASKMANAGER_TASKVIEW_ADD_TASK_EXTININFO = 'TASKMANAGER_TASKVIEW_ADD_TASK_EXTININFO';
export const TASKMANAGER_TASKVIEW_GET_TASK_EXTININFO = 'TASKMANAGER_TASKVIEW_GET_TASK_EXTININFO';
export const TASKMANAGER_TASKVIEW_GET_TASK_STATISTICS = 'TASKMANAGER_TASKVIEW_GET_TASK_STATISTICS';
export const TASKMANAGER_REPORT_CREATE_REPORT = 'TASKMANAGER_REPORT_CREATE_REPORT';
export const TASKMANAGER_REPORT_TEMPLATE_LIST = 'TASKMANAGER_REPORT_TEMPLATE_LIST';
export const TASKMANAGER_DATALIST_DATA_LIST = 'TASKMANAGER_DATALIST_DATA_LIST';
export const TASKMANAGER_TASK_DATA_BY_DEVICE = 'TASKMANAGER_TASK_DATA_BY_DEVICE';
export const TASKMANAGER_CLEAR_ON_CLOSE = 'TASKMANAGER_CLEAR_ON_CLOSE';

//智能传感器数据服务
export const SSD_DATALIST_DATA_LIST = 'SSD_DATALIST_DATA_LIST';
export const SSD_DATALIST_DATA_DATA_TYPE = 'SSD_DATALIST_DATA_DATA_TYPE';
export const SSD_DATALIST_DATA_SINGLE_DETAILS = 'SSD_DATALIST_DATA_SINGLE_DETAILS';
export const SSD_DATALIST_DATA_LASTEST_DETAILS = 'SSD_DATALIST_DATA_LASTEST_DETAILS';
export const SSD_DATALIST_DATA_LASTEST_DETAILS_SHOW = 'SSD_DATALIST_DATA_LASTEST_DETAILS_SHOW';
export const SSD_DATALIST_LASTEST_DATA_LIST = 'SSD_DATALIST_LASTEST_DATA_LIST';
export const SSD_DATALIST_CAROUSEL_DATA = 'SSD_DATALIST_CAROUSEL_DATA';
export const SSD_DATALIST_MEDIA_DATA = 'SSD_DATALIST_MEDIA_DATA';
export const SSD_DATALIST_MECH_CHART_DATA = 'SSD_DATALIST_MECH_CHART_DATA';
export const SSD_DATALIST_TRENDS_TEST_POINT = 'SSD_DATALIST_TRENDS_TEST_POINT';
export const SSD_DATALIST_TRENDS_MULTI_TEST_POINTS = 'SSD_DATALIST_TRENDS_MULTI_TEST_POINTS';
export const SSD_DATALIST_TRENDS_VALUE_TYPE = 'SSD_DATALIST_TRENDS_VALUE_TYPE';
export const SSD_REPORT_TEMPLATE_LIST = 'SSD_REPORT_TEMPLATE_LIST';
export const SSD_REPORT_CREATE_NEW_REPORT = 'SSD_REPORT_CREATE_NEW_REPORT';

//系统管理-用户注册
export const SYSTEM_REGIS_GET_CODE = 'SYSTEM_REGIS_GET_CODE';
export const SYSTEM_REGIS_CONFIRM = 'SYSTEM_REGIS_CONFIRM';
//系统管理-用户
export const SYSTEM_USER_GET_USER_INFO = 'SYSTEM_USER_GET_USER_INFO';
export const SYSTEM_USER_ADD_USER_INFO = 'SYSTEM_USER_ADD_USER_INFO';
export const SYSTEM_USER_UPDATE_USER_INFO = 'SYSTEM_USER_UPDATE_USER_INFO';
export const SYSTEM_USER_DELETE_USER_INFO = 'SYSTEM_USER_DELETE_USER_INFO';
export const SYSTEM_USER_MODIFY_PASSWORD = 'SYSTEM_USER_MODIFY_PASSWORD';
export const SYSTEM_USER_GET_BY_STR = 'SYSTEM_USER_GET_BY_STR';
export const SYSTEM_USER_PASSWORD_RESET = 'SYSTEM_USER_PASSWORD_RESET';
export const CLEAR_SYSTEM_USER_GET_BY_STR = 'CLEAR_SYSTEM_USER_GET_BY_STR';

//系统管理-重置密码
export const SYSTEM_RESET_CAPTCHA = 'SYSTEM_RESET_CAPTCHA';
export const SYSTEM_RESET_GET_ADDR = 'SYSTEM_RESET_GET_ADDR';

//系统管理-用户组
export const SYSTEM_USER_GROUP_GET_USER_GROUP = 'SYSTEM_USER_GROUP_GET_USER_GROUP';
export const SYSTEM_USER_GROUP_DELETE_USER_GROUP = 'USERCENTER_USERGROUP_DELETE';
export const SYSTEM_USER_GROUP_UPDATE_USER_GROUP = 'SYSTEM_USER_GROUP_UPDATE_USER_GROUP';
export const SYSTEM_USER_GROUP_ADD_USER_GROUP = 'SYSTEM_USER_GROUP_ADD_USER_GROUP';
export const SYSTEM_USER_GROUP_GET_USER_GROUP_BY_COMPANY =
    'SYSTEM_USER_GROUP_GET_USER_GROUP_BY_COMPANY';
export const SYSTEM_USER_GROUP_GET_USER_GROUP_MENUS = 'SYSTEM_USER_GROUP_GET_USER_GROUP_MENUS';
export const SYSTEM_USER_GROUP_SEARCH_USER_GROUP = 'SYSTEM_USER_GROUP_SEARCH_USER_GROUP';
export const SYSTEM_USER_GROUP_USERMENU = 'SYSTEM_USER_GROUP_USERMENU';

//系统管理-数据权限
export const SYSTEM_RECORD_GROUP_GET_RECORD_GROUP = 'SYSTEM_RECORD_GROUP_GET_RECORD_GROUP';
export const SYSTEM_RECORD_GROUP_ADD_RECORD_GROUP = 'SYSTEM_RECORD_GROUP_ADD_RECORD_GROUP';
export const SYSTEM_RECORD_GROUP_UPDATE_RECORD_GROUP = 'SYSTEM_RECORD_GROUP_UPDATE_RECORD_GROUP';
export const SYSTEM_RECORD_GROUP_DELETE_RECORD_GROUP = 'SYSTEM_RECORD_GROUP_DELETE_RECORD_GROUP';
export const SYSTEM_RECORD_GROUP_GET_RECORD_GROUP_BY_ID =
    'SYSTEM_RECORD_GROUP_GET_RECORD_GROUP_BY_ID';
export const SYSTEM_RECORD_GROUP_GET_RECORD_INFO_BY_COMPANY_ID =
    'SYSTEM_RECORD_GROUP_GET_RECORD_INFO_BY_COMPANY_ID';
export const SYSTEM_RECORD_GROUP_QUERY_RECORD_GROUP = 'SYSTEM_RECORD_GROUP_QUERY_RECORD_GROUP';

//数据文件解析服务
export const PARSEFILE_GET_DRAW_DATA = 'PARSEFILE_GET_DRAW_DATA';
export const PARSEFILE_GET_DRAW_DATA_SHOW = 'PARSEFILE_GET_DRAW_DATA_SHOW';
export const PARSEFILE_GET_DIAGIMAGE_INFO = 'PARSEFILE_GET_DIAGIMAGE_INFO';

//系统日志
export const SYSTEM_MANAGER_LOG_GETLOG = 'SYSTEM_MANAGER_LOG_GETLOG';

//系统管理-菜单
export const SYSTEM_GET_SYS_MENU = 'SYSTEM_GET_SYS_MENU';

//文件管理 -- 获取资源文件
export const FILEMANAGER_DOWNLOAD = 'FILEMANAGER_DOWNLOAD';
export const FILEMANAGER_GET_RESOURCE = 'FILEMANAGER_GET_RESOURCE';
export const FILEMANAGER_DIAGNOSIS_INFO = 'STATISTICS_DIAGNOSIS_INFO';

//综合统计
export const STATISTICS_SUMMARY = 'STATISTICS_SUMMARY';
export const STATISTICS_STATUS_SUBSTATION = 'STATISTICS_STATUS_SUBSTATION';
export const STATISTICS_ABNORMALRATIO_SUBSTATION = 'STATISTICS_ABNORMALRATIO_SUBSTATION';
export const STATISTICS_DEVICESTATUS = 'STATISTICS_DEVICESTATUS';
export const STATISTICS_ABNORMALRATIO_DEVICE = 'STATISTICS_ABNORMALRATIO_DEVICE';
export const STATISTICS_STATUS_SUBSTATIONBYCOMPANY = 'STATISTICS_STATUS_SUBSTATIONBYCOMPANY';
export const STATISTICS_ABNORMALPROCESS_DEVICE = 'STATISTICS_ABNORMALPROCESS_DEVICE';
export const STATISTICS_STATUS_COMPANY = 'STATISTICS_STATUS_COMPANY';
export const STATISTICS_SSD_TESTPOINT = 'STATISTICS_SSD_TESTPOINT';
export const STATISTICS_SSD_CHANNEL = 'STATISTICS_SSD_CHANNEL';
export const STATISTICS_SSD_SUBSTATIONSTATUS = 'STATISTICS_SSD_SUBSTATIONSTATUS';
export const STATISTICS_SSD_TASKCOUNT = 'STATISTICS_SSD_TASKCOUNT';
export const STATISTICS_SSD_TASKSTATUS = 'STATISTICS_SSD_TASKSTATUS';
export const STATISTICS_SSD_TASKCALENDAR = 'STATISTICS_SSD_TASKCALENDAR';
export const STATISTICS_SSD_MONITOR_AND_ADU = 'STATISTICS_SSD_MONITOR_AND_ADU';
export const STATISTICS_SSD_DEVICESTATUS = 'STATISTICS_SSD_DEVICESTATUS';
export const STATISTICS_SSD_TESTPOINTSTATUS = 'STATISTICS_SSD_TESTPOINTSTATUS';
export const STATISTICS_SSD_TESTPOINTSTATUS_SHOW = 'STATISTICS_SSD_TESTPOINTSTATUS_SHOW';
export const STATISTICS_PERSONAL_INFORMATION = 'STATISTICS_PERSONAL_INFORMATION';
export const STATISTICS_ARCHIVE_STATUS = 'STATISTICS_ARCHIVE_STATUS';
export const STATISTIC_TEST_POINT_STATUS = 'STATISTICS_TEST_POINT_STATUS';
export const STATISTIC_TASK_DEVICE_STATUS = 'STATISTIC_TASK_DEVICE_STATUS';
export const STATISTICS_ALARMINFO_SUBSTATION = 'STATISTICS_ALARMINFO_SUBSTATION';
export const STATISTICS_ALARMINFO_DEVICE = 'STATISTICS_ALARMINFO_DEVICE';
export const STATISTICS_ALARMINFO_POINT = 'STATISTICS_ALARMINFO_POINT';
export const STATISTICS_CLEAR_SUBSTATIONDATADETAILS = 'STATISTICS_CLEAR_SUBSTATIONDATADETAILS';
export const COMMON_DESTROY_POINTDATADETAILS = 'COMMON_DESTROY_POINTDATADETAILS';
export const STATISTICS_SVG_SELECTED_POINT_LIST = 'STATISTICS_SVG_SELECTED_POINT_LIST';
export const CLEAR_STATISTICS_TASK_DATA = 'CLEAR_STATISTICS_TASK_DATA';
export const CLEAR_STATISTICS_SSD_DATA = 'CLEAR_STATISTICS_SSD_DATA';

//工作台
export const WORKBENCH_GET_ACTIVE_MSG = 'WORKBENCH_GET_ACTIVE_MSG';
export const WORKBENCH_GET_CURRENT_TASK = 'WORKBENCH_GET_CURRENT_TASK';

/**
 * 以下Type是在服务端接口没有实现情况下模拟用的
 * -------------------------------------------------------------------------------------------------------------------------
 */

//案例库获取数据列表
export const SPECIFICATIONS_CASELIB_GET_INFO = 'SPECIFICATIONS_CASELIB_GET_INFO';
//获取变电站公司列表getArchive
export const SPECIFICATIONS_GET_ARCHIVE = 'SPECIFICATIONS_GET_ARCHIVE';
//获取变电站公司列表getArchive
export const SPECIFICATIONS_GET_ARCHIVE_LEVEL = 'SPECIFICATIONS_GET_ARCHIVE_LEVEL';
//获取变电站公司列表getArchive
export const SPECIFICATIONS_GET_ARCHIVE_THREE = 'SPECIFICATIONS_GET_ARCHIVE_THREE';
//获取技术培训列表
export const SPECIFICATIONS_GET_GETTRAININGMATERIALIST =
    'SPECIFICATIONS_GET_GETTRAININGMATERIALIST';
//新增或者更新技术培训文件
export const SPECIFICATIONS_ADDUPDATE_SPECIFICATIONS_TRAININGMATERIALIST =
    'SPECIFICATIONS_ADDUPDATE_SPECIFICATIONS_TRAININGMATERIALIST';
//删除技术培训
export const PECIFICATIONS_DELETE_TRAINING = 'PECIFICATIONS_DELETE_TRAINING';
//技术培训-上传
export const SPECIFICATIONS_UPLOAD_TRAININGMATERIALIST =
    'SPECIFICATIONS_UPLOAD_TRAININGMATERIALIST';
//获取导则规范列表
export const SPECIFICATIONS_GET_GETGUIDELIST = 'SPECIFICATIONS_GET_GETGUIDELIST';
//获取变电站列表
export const SPECIFICATIONS_GET_SUBSTATION_LIST = 'SPECIFICATIONS_GET_SUBSTATION_LIST';
//获取设备列表
export const SPECIFICATIONS_GET_GETDEVICEBYCONDITION = 'SPECIFICATIONS_GET_GETDEVICEBYCONDITION';
//获取用户列表
export const SPECIFICATIONS_GET_GETUSERS = 'SPECIFICATIONS_GET_GETUSERS';
//获取监测设备列表
export const SPECIFICATIONS_GET_GETYCSBLIST = 'SPECIFICATIONS_GET_GETYCSBLIST';
//获取状态监测类型
export const SPECTICATIONS_GET_GETBYKINDTYPE = 'SPECTICATIONS_GET_GETBYKINDTYPE';
//新建案例库
export const SPECTICATIONS_NEW_CREATE_CASELIB = 'SPECTICATIONS_NEW_CREATE_CASELIB';
//新建技术培训
export const SPECTICATIONS_NEW_CREATE_TECHTRAIN = 'SPECTICATIONS_NEW_CREATE_TECHTRAIN';
//新建导则规范
export const SPECTICATIONS_NEW_GUIDEDOC = 'SPECTICATIONS_NEW_GUIDEDOC';

export const SPECIFICATIONS_ADD_UPDATE_CASELIB = 'SPECIFICATIONS_ADD_UPDATE_CASELIB';
//删除案例库
export const SPECIFICATIONS_DELETE_CASELIB = 'SPECIFICATIONS_DELETE_CASELIB';

export const SPECIFICATIONS_ADD_UPDATE_GUIDE_LINE = 'SPECIFICATIONS_ADD_UPDATE_GUIDE_LINE';

export const SPECIFICATIONS_DELETE_GUIDE_LINE = 'SPECIFICATIONS_DELETE_GUIDE_LINE';
//指纹库 查询列表
export const SPECIFICATIONS_FINGER_PRINT_LIST = 'POST_SPECIFICATIONS_FINGER_PRINT_LIST';

//监测主机
export const ARCHIVE_SENSOR_INFO = 'ARCHIVE_SENSOR_INFO';
export const ARCHIVE_SENSOR_HOST_INFO = 'ARCHIVE_SENSOR_HOST_INFO';
export const ARCHIVE_SENSOR_UPDATE_MONITOR_VALID = 'ARCHIVE_SENSOR_UPDATE_MONITOR_VALID';
export const ARCHIVE_SENSOR_COLLECT_DATA_ISSUED = 'ARCHIVE_SENSOR_COLLECT_DATA_ISSUED';
export const ARCHIVE_SENSOR_MONITOR_GET_STATUS = 'ARCHIVE_SENSOR_MONITOR_GET_STATUS';

//系统-获取告警级别
export const SYSTEM_ALARM_LEVEL_CUSTOM = 'SYSTEM_ALARM_LEVEL_CUSTOM';
export const SYSTEM_ALARM_LEVEL_CUSTOM_ADD = 'SYSTEM_ALARM_LEVEL_CUSTOM_ADD';
export const SYSTEM_ALARM_LEVEL_CUSTOM_UPDATE = 'SYSTEM_ALARM_LEVEL_CUSTOM_UPDATE';
export const SYSTEM_ALARM_LEVEL_CUSTOM_DELETE = 'SYSTEM_ALARM_LEVEL_CUSTOM_DELETE';

export const ARCHIVE_SINGLE_THRESHOLD_ADD = 'ARCHIVE_SINGLE_THRESHOLD_ADD';
export const ARCHIVE_SINGLE_THRESHOLD_QUERY = 'ARCHIVE_SINGLE_THRESHOLD_QUERY';
export const ARCHIVE_THRESHOLD_UPDATE = 'ARCHIVE_THRESHOLD_UPDATE';
export const ARCHIVE_THRESHOLD_DELETE = 'ARCHIVE_THRESHOLD_DELETE';
export const ARCHIVE_TESTPOINT_RULE = 'ARCHIVE_TESTPOINT_RULE';
export const ARCHIVE_TESTPOINT_RULE_ADD = 'ARCHIVE_TESTPOINT_RULE_ADD';
export const ARCHIVE_TESTPOINT_RULE_DELETE = 'ARCHIVE_TESTPOINT_RULE_DELETE';
export const ARCHIVE_TESTPOINT_RULE_UPDATE = 'ARCHIVE_TESTPOINT_RULE_UPDATE';

export const ARCHIVE_RULES_AE = 'ARCHIVE_RULES_AE';
export const ARCHIVE_RULES_AE_ADD = 'ARCHIVE_RULES_AE_ADD';
export const ARCHIVE_RULES_AE_DELETE = 'ARCHIVE_RULES_AE_DELETE';
export const ARCHIVE_RULES_AE_UPDATE = 'ARCHIVE_RULES_AE_UPDATE';

//样本库-获取预样本库列表
export const SAMPLELIB_GET_PRE_LISTS = 'SAMPLELIB_GET_PRE_LISTS';
//样本库-获取样本库列表
export const SAMPLE_GET_SAMPLE_LIST = 'SAMPLE_GET_SAMPLE_LIST';
//样本库-获取算法列表
export const SAMPLE_GET_ALGORITHMTRAINING_LIST = 'SAMPLE_GET_ALGORITHMTRAINING_LIST';
//样本库-获取标签列表
export const SAMPLE_GET_LABEL_LIST_SYSTEM = 'SAMPLE_GET_LABEL_LIST_SYSTEM';
export const SAMPLELIB_GET_PRE_LISTS_CLEAR = 'SAMPLELIB_GET_PRE_LISTS_CLEAR';
export const SAMPLE_GET_SAMPLE_STATISTIC = 'SAMPLE_GET_SAMPLE_STATISTIC';
export const SAMPLE_GET_LABEL_LIST_CUSTOM = 'SAMPLE_GET_LABEL_LIST_CUSTOM';
export const SAMPLE_MODIFY_LABEL_CUSTOM = 'SAMPLE_MODIFY_LABEL_CUSTOM';
export const SAMPLE_ADD_LABEL_CUSTOM = 'SAMPLE_ADD_LABEL_CUSTOM';
export const SAMPLE_DELTE_LABEL_CUSTOM = 'SAMPLE_DELTE_LABEL_CUSTOM';
export const SAMPLE_DELTE_PRE_SAMPLE = 'SAMPLE_DELTE_PRE_SAMPLE';
export const SAMPLE_ADOPT_SAMPLE = 'SAMPLE_ADOPT_SAMPLE';
export const SAMPLE_BIND_TAG = 'SAMPLE_BIND_TAG';

//算法训练-算法列表
export const ALGORITHM_LIST = 'ALGOTITHM_LIST';
//算法训练-算法生效
export const ALGORITHM_STATE_UPDATE = 'ALGORITHM_STATE_UPDATE';
//算法训练-开始训练
export const ALGORITHM_TRAIN = 'ALGORITHM_TRAIN';
//算法训练-结束训练
export const ALGORITHM_STOP = 'ALGORITHM_STOP';
//算法训练-获取算法训练状态
export const ALGORITHM_STATE = 'ALGORITHM_STATE';
export const ALGORITHM_CURRENT_USED_VERSION = 'ALGORITHM_CURRENT_USED_VERSION';

//控制命令
export const CONTROL_COMMAND_SUCCESS = 'CONTROL_COMMAND_SUCCESS';
//
export const COMMAND_SUBMIT = 'COMMAND_SUBMIT';

export const STATISTICS_TASK_RESULT = 'STATISTICS_TASK_RESULT';
export const STATISTICS_FAILURE_CASE = 'STATISTICS_FAILURE_CASE';
export const STATISTICS_SSD_DEVICE_INFO = 'STATISTICS_SSD_DEVICE_INFO';
export const STATISTICS_TASK_DEVICE_STATUS_BY_DEVICE_TYPE =
    'STATISTICS_TASK_DEVICE_STATUS_BY_DEVICE_TYPE';
export const SYSTEM_ALARM_CONFIG_INSERT = 'SYSTEM_ALARM_CONFIG_INSERT';
export const SYSTEM_GET_USERGROUP_BY_COMPANYID = 'SYSTEM_GET_USERGROUP_BY_COMPANYID';
export const SYSTEM_USER_AUTHORITY_SET = 'SYSTEM_USER_AUTHORITY_SET';
export const SYSTEM_ALARM_CONFIG_QUERY = 'SYSTEM_ALARM_CONFIG_QUERY';
export const SYSTEM_ALARM_LIST_QUERY = 'SYSTEM_ALARM_LIST_QUERY';
export const SYSTEM_ALARM_CONFIG_UPDATE = 'SYSTEM_ALARM_CONFIG_UPDATE';
export const SYSTEM_ALARM_CONFIG_DELETE = 'SYSTEM_ALARM_CONFIG_DELETE';
export const SYSTEM_ALARM_LIST_RESEND = 'SYSTEM_ALARM_LIST_RESEND';
